### PR TITLE
Use modern APT keyrings on Debian family

### PR DESCRIPTION
**Pull request by smortex**
This makes use of puppetlabs/puppetlabs-apt#1128 to store the public key
in `/etc/apt/keyrings` and add a `signed-by` option to the
`sources.list.d` entry.

### CODE REVIEW

**Comment by smortex** [comment]
This prevent this deprecation warning on Debian 12 (for which AIO packages are still not available so not part of the CI test matrix for now, but this is another problem):

```
W: https://ose-repo.syslog-ng.com/apt/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Review by faxm0dem — APPROVED** [review]
LGTM !

**Comment by smortex** [comment]
Relevant discussion:
https://github.com/puppetlabs/puppetlabs-postgresql/pull/1563#pullrequestreview-1827072156

Embedding the key in the module is a bit "meh", but in case of compromission of the repo, fetching a rogue key and installing rogue packages is not as straightforward…

**Comment by smortex** [comment]
I reworked the PR to include a copy of the key in the module.  Feels better IMHO.

**Review by faxm0dem — APPROVED** [review]
:+1:

**Pull request merged**
